@Host = http://localhost:5209/api/categories

### Insert

Post {{Host}}
Content-type: application/json
{
  "name": "Offering"
}

### Get All

GET {{Host}}
Accept: application/json


### Search by Id

GET {{Host}}/019fd3cd-b211-7c40-98f6-7528306eecde
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019fd3cd-b211-7c40-98f6-7528306eecde
Content-type: application/json
{
  "name": "Seed"
}

###