@Host = https://localhost:7002/api/categories

### Insert

Post {{Host}}
Content-type: application/json
{
  "name": "First Fruit"
}

### Get All

GET {{Host}}
Accept: application/json
Authorization: Bearer CfDJ8PfHF7c39m1PkvdWDB84NFz_wlEe2V3qcymBelSU5ZIY5OjngIa39dIoJIOyRfL_IOW2izmICAoKo77AWqvJFdr0Il-eiEtDm84c5CR9k55sHP1XWTSKAl6TsB8iSnzpcxtse_6k-k70-7dl-NHxlWYYT_ORNignwstIqBLcB5klZ9a2eih0u2TMPjuAFfqZ1iLEvSVsnVd0gTKIN5VM_FFsShGy4NWZoDTQJoVGHdTMdaEg4y9iZu7iLXlJw5jJxIzdpQukvhRee0VNlnPtI37_owh5zuYKucoy49AW321qvoV_M-6xHZYHD5z49eCreswTrjksW6g8xEeSocxodpwm2ILEntKdjELRdeWvKbBpzGZMVP5xA9XuXZIGwuBp_AudVya2dSyhjAA5O1WfgMRZM-vC7rXJjev66L4J0a3jAVflmAqIx--IxrJLMXh8H7hnIrUQ9mi0tdTPrRmkNUmZtFpg-3NYzTmferEzkB3fjh5ROStzFAzil42csTii3FVCf-feGHTCxrumm0RaVxSA173bl_zh7qZPbnadz1lfzpvtV7Dx1KFrxhfp19PWYuWEsgTajsvkRZleGuD7shoRIBuynVqEDgrpEUSBoPOQSP1BZKxjPDO8xCMADtHclbYdHM-DmNCq33xaupaD1tgyZ0xVIn8IkLX7EmM-G80daP-VJbD92kJmzcg-FxRA1uRrvbqZxuMQubQ6fsK9hwQ

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json


### Search by Id

GET {{Host}}/019fd3cd-b211-7c40-98f6-7528306eecde
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019fd3cd-b211-7c40-98f6-7528306eecde
Content-type: application/json
{
  "name": "Seed"
}

### Temporarily Delete by Id

DELETE {{Host}}/019fd42c-36ec-79c7-a5b2-c97434dae310

### Restore by Id

PUT {{Host}}/019fd3ce-1039-76ee-bb68-200a6ff198f6/restore

### Permanently Delete by Id

DELETE {{Host}}/019fd42c-36ec-79c7-a5b2-c97434dae310/permanent