@Host = https://localhost:7002/api/documents

### Insert

Post {{Host}}
Content-type: application/json
{
  "name": "2026 Financial Report",
  "blobName": "2026-FR-document.pdf",
  "documentType": 0
}

### Get All

GET {{Host}}
Accept: application/json

### Search by Id

GET {{Host}}/019ffcc9-a40a-739e-a14a-65ae2d0f3225
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019ffcc9-a40a-739e-a14a-65ae2d0f3225
Content-type: application/json
{ 
  "name": "2025 Financial Report",
  "blobName": "2025-FR-document.pdf",
  "documentType": 1
}

### Temporarily Delete by Id

DELETE {{Host}}/019ffcc9-a40a-739e-a14a-65ae2d0f3225

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json

### Restore by Id

PUT {{Host}}/019ffcc9-a40a-739e-a14a-65ae2d0f3225/restore

### Permanently Delete by Id

DELETE {{Host}}/019ffcc9-a40a-739e-a14a-65ae2d0f3225/permanent