@Host = http://localhost:5209/api/expenditures

### Insert

Post {{Host}}
Content-type: application/json
{
  "summary": "Seed",
  "amount": 50.0,
  "date": "2026-08-18T10:45:00"
}

### Get All

GET {{Host}}
Accept: application/json

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json


### Search by Id

GET {{Host}}/019fe626-cf89-7aab-b6ee-2d9d909e53a6
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019fe627-8051-7320-9fa7-7d2595b0dd97
Content-type: application/json
{
  "summary": "Unknown",
  "amount": 20.0,
  "date": "2026-07-31T10:15:00"
}

### Temporarily Delete by Id

DELETE {{Host}}/019fe627-8051-7320-9fa7-7d2595b0dd97

### Restore by Id

PUT {{Host}}/019fe627-8051-7320-9fa7-7d2595b0dd97/restore

### Permanently Delete by Id

DELETE {{Host}}/019fe627-8051-7320-9fa7-7d2595b0dd97/permanent