@Host = http://192.168.0.195:7200/api/financial-summary-monthly-reports

### Insert

Post {{Host}}
Content-type: application/json
{
  "month": 8,
  "year": 2026,
  "openingBalance": 500
}

### Get All

GET {{Host}}
Accept: application/json


### Search by Id

GET {{Host}}/01a0ef74-2c29-7d75-b91b-1f5f1e60e729
ACCEPT: application/json

### Update by Id

PUT {{Host}}/01a0ef74-2c29-7d75-b91b-1f5f1e60e729
Content-type: application/json
{  
  "month": 9,
  "year": 2026,
  "openingBalance": 590
}

### Permanently Delete by Id

DELETE {{Host}}/01a0f1f4-0151-77aa-9a4e-5d9b944afe26/permanent


### Monthly PDF by Id

GET {{Host}}/01a10dc5-e732-740d-99e0-b8801d8e2476/pdf-data