@Host = https://localhost:7002/api/givings

### Insert

Post {{Host}}
Content-type: application/json
{
  "Amount": 100.0,
  "Date": "2026-08-09T09:00:00",
  "Summary": "Test giving",
  "MeetingId": "019FE827-9FDB-7E9E-8041-B5A06C836118",
  "CategoryId": "019FD3CD-B211-7C40-98F6-7528306EECDE"
}

### Get All

GET {{Host}}
Accept: application/json

### Search by Id

GET {{Host}}/019ff619-85ac-7559-a0ab-068e0d67e15e
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019ff619-85ac-7559-a0ab-068e0d67e15e
Content-type: application/json
{
  "Amount": 30.0,
  "Date": "2026-08-09T09:00:00",
  "Summary": "Giving to church building project.",
  "MeetingId": "019FE827-9FDB-7E9E-8041-B5A06C836118",
  "CategoryId": "019ff830-c06d-7cfc-b24d-3ed15a5270e7"
}

### Temporarily Delete by Id

DELETE {{Host}}/019ff619-85ac-7559-a0ab-068e0d67e15e

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json

### Restore by Id

PUT {{Host}}/019ff619-85ac-7559-a0ab-068e0d67e15e/restore

### Permanently Delete by Id

DELETE {{Host}}/019ff619-85ac-7559-a0ab-068e0d67e15e/permanent