@Host = http://localhost:5209/api/meetings

### Insert

Post {{Host}}
Content-type: application/json
{
  "date": "2026-01-17T10:00:00",
  "summary": "Normal service",
  "messageTitle": "The Holy Spirit",
  "minister": "Carey Smith",
  "noOfMaleAttendance": 11,
  "noOfFemaleAttendance": 5,
  "noOfChildrenAttendance": 5
}

### Get All

GET {{Host}}
Accept: application/json

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json


### Search by Id

GET {{Host}}/019fe83d-9234-7a08-b2f4-0ac2b710e3ff
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019fd3cd-b211-7c40-98f6-7528306eecde
Content-type: application/json
{
  "name": "Seed"
}

### Temporarily Delete by Id

DELETE {{Host}}/019fd42c-36ec-79c7-a5b2-c97434dae310

### Restore by Id

PUT {{Host}}/019fd3ce-1039-76ee-bb68-200a6ff198f6/restore

### Permanently Delete by Id

DELETE {{Host}}/019fd42c-36ec-79c7-a5b2-c97434dae310/permanent