@Host = https://localhost:7002/api/meeting-categories

### Insert

Post {{Host}}
Content-type: application/json
{
  "name": "Healing Service"
}

### Get All

GET {{Host}}
Accept: application/json

### Search by Id

GET {{Host}}/01a067c2-5d0e-79e2-b078-462a5829162d
ACCEPT: application/json

### Update by Id

PUT {{Host}}/01a067c2-5d0e-79e2-b078-462a5829162d
Content-type: application/json
{
  "name": "Prayer Meeting"
}

### Temporarily Delete by Id

DELETE {{Host}}/01a067c2-5d0e-79e2-b078-462a5829162d


### Get All Deleted

GET {{Host}}/deleted
Accept: application/json

### Restore by Id

PUT {{Host}}/01a067c2-5d0e-79e2-b078-462a5829162d/restore

### Permanently Delete by Id

DELETE {{Host}}/01a067c2-5d0e-79e2-b078-462a5829162d/permanent