@Host = http://localhost:5209/api/members

### Insert

Post {{Host}}
Content-type: application/json
{
  "firstName": "Testing",
  "lastName": "Testing",
  "address": "86 Akazienalle St",
  "phoneNumber": "+4915018548300",
  "positionId": "019FE1C0-19D4-72C3-8023-1C2C6546B48F"
}

### Get All

GET {{Host}}
Accept: application/json

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json


### Search by Id

GET {{Host}}/019fefb8-9fed-7137-83cd-be5a3ffc9771
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019fefb8-9fed-7137-83cd-be5a3ffc9771
Content-type: application/json
{
  "firstName": "Testing",
  "lastName": "Testing",
  "address": "40 Akazienalle St",
  "phoneNumber": "+4915018548300",
  "positionId": "019FE1C0-324C-7DAC-B1BA-940C1A5BA4AB"
}

### Temporarily Delete by Id

DELETE {{Host}}/019fefb8-9fed-7137-83cd-be5a3ffc9771

### Restore by Id

PUT {{Host}}/019fd3ce-1039-76ee-bb68-200a6ff198f6/restore

### Permanently Delete by Id

DELETE {{Host}}/019fd42c-36ec-79c7-a5b2-c97434dae310/permanent