@Host = https://localhost:7002/api/positions

### Insert

Post {{Host}}
Content-type: application/json
{
  "name": "Worker"
}

### Get All

GET {{Host}}
Accept: application/json

### Get All Deleted

GET {{Host}}/deleted
Accept: application/json


### Search by Id

GET {{Host}}/019fe1c0-324c-7dac-b1ba-940c1a5ba4ab
ACCEPT: application/json

### Update by Id

PUT {{Host}}/019fde4a-be8b-78e0-b0c4-665b1cdd9fdf
Content-type: application/json
{
  "name": "Pastor"
}

### Temporarily Delete by Id

DELETE {{Host}}/019fe1c0-324c-7dac-b1ba-940c1a5ba4ab

### Restore by Id

PUT {{Host}}/019fe23b-6128-76ba-bfa2-b9d9726e2877/restore

### Permanently Delete by Id

DELETE {{Host}}/019fe23b-6128-76ba-bfa2-b9d9726e2877/permanent