@Host = https://localhost:7002

### Insert

POST {{Host}}/register
content-type: application/json
{
  "email":"mfm@gmail.com",
  "password":"20Mfm26ms@"
}

### Login

POST {{Host}}/login
content-type: application/json
{
  "email":"mfm@gmail.com",
  "password":"20Mfm26ms@"
}