@Host = http://localhost:5209/api/members

### Insert

POST {{Host}}/register
content-type: application/json
{
  "email":"isoboyedanobu@gmail.com",
  "password":"20Dc26ms@"
}

### Login

POST {{Host}}/login
content-type: application/json
{
  "email":"isoboyedanobu@gmail.com",
  "password":"20Dc26ms@"
}