@Host = http://192.168.0.195:7200

### Insert

POST {{Host}}/register
content-type: application/json
{
  "email":"mfm@gmail.com",
  "password":"20Mfm26ms@"
}

### Login

POST {{Host}}/login
content-type: application/json
{
  "email":"mfm@gmail.com",
  "password":"20Mfm26ms@"
}

### Test Claims

GET {{Host}}/api/security-test/claims
Accept: application/json